### ISSUE TITLE
Implement architecture for 4.0

### ISSUE THREAD

**Issue by goloroden** [thenativeweb/wolkenkit#181]
### What is this epic about?

This epic describes the way to the new architecture of wolkenkit 4.0.

```
                  Queuestore      Eventstore
                      ^               ^
                      |               |
                      ^               ^
-> Command >---> Dispatcher ----->> Domain
                      ^               v
                      |               |
                      ^               |
                    Flow              |       
                      ^               |
                      |               |
                      ^               |
                 Dispatcher <-----+   |
                                  |   |
                                  ^   v                      
<- Event <---------------------< Publisher
                                      v   
                                      |
                                      v   
                                 Projection
                                      v
                                      |
                                      v
<- Query <<--------------------< Liststore
                                 Graphstore
                                 Treestore
                                 ...
```

The new application structure (as pseudo-code) looks like this:

```
/app
  /server
    /domain
      /planning
        peerGroup.js
    /views
      peerGroups.js
```

### What needs to be done to complete this epic?

- [ ] Implement the servers
  - [x] Health
  - [x] Command
    - [x] `POST /commands`
    - [x] `GET /commands/configuration`
  - [x] Event
    - [x] `GET /events`
    - [x] `GET /events/configuration`
  - [ ] Query
    - [ ] `GET /queries/configuration`
    - [ ] `GET /queries/:view/:query`, e.g. `users/top-50-by-country` or `peerGroups/all`
    - [ ] `GET /queries/:view/:query/notifications`
  - [x] Domain
  - [ ] Projection
  - [ ] Flow
  - [x] Dispatcher
  - [x] Publisher
  - [ ] Queuestore
  - [x] Eventstore
  - [ ] Liststore
  - [ ] Graphstore
  - [ ] Treestore

### What else should we know?

We do not yet know whether there is only a single dispatcher, or if the two dispatchers are separate types of servers.

It also may make sense to extract the eventstore to an HTTP server of its own (see #100 for details).
