### ISSUE TITLE
Introduce export and import commands for backup and restore

### ISSUE THREAD

**Issue by goloroden** [thenativeweb/wolkenkit#62]
### What is this epic about?

Right now there is no option in the wolkenkit CLI to backup and restore an application's data, such as the events from the event store and the files from depot. To allow backing up and restoring, and maybe also migrating data from one system to another, we should introduce two new commands to the CLI, `export` and `import`:

```shell
$ wolkenkit export --env default --to <directory> --from-event-store true
$ wolkenkit import --env default from <directory>
```

### What needs to be done to complete this epic?

- [x] Implement the export command
  - [x] Handle flags
    - [x] Use `default` as the default environment
    - [x] Use `true` as the default value for `from-event-store`
  - [x] Handle the target directory
    - [x] Fail if it exists, but it isn't empty
    - [x] Create it if it doesn't exist yet
  - [x] Fetch all data from the event store
  - [x] Transform the events to JSON
  - [x] Store the JSON events as files in `<directory>/event-store`
    - [x] Store the events in batches of 65.536 events per file
    - [x] Name the files `events-0000000000000001.json` (and so on)
- [x] Implement the import command
  - [x] Handle flags
    - [x] Use `default` as the default environment
  - [x] Handle the source directory
    - [x] Fail if it doesn't exist
    - [x] Fail if it exists, but does not contain the correct file structure
    - [x] Fail if the target event store isn't empty
  - [x] Read all events using streams
  - [x] Write them to the event store
- [x] Add tests
- [x] Add documentation
