### ISSUE TITLE
Make wolkenkit run on Raspberry Pi

### ISSUE THREAD

**Issue by goloroden** [thenativeweb/wolkenkit#67]
### What is this epic about?

Since Docker runs on Raspberry Pi, it would be great if you could also run wolkenkit on Raspberry Pi. This would allow us to provide an image that you can download that contains Docker and all the required wolkenkit Docker images. This could be a highly interesting thing for tinkering and IoT solutions.

### What needs to be done to complete this epic?

- [ ] Verify the compatibility of the various wolkenkit components with Raspberry Pi
  - [ ] Find alternatives if needed
- [ ] Figure out how to deal the limited resources of the Raspberry Pi
- [ ] Create an image
  - [ ] Define where to offer this as download
- [ ] Add tests
- [ ] Add documentation

**Comment by goloroden** [comment]
Will be solved by the multiple-runtimes feature in v4, hence closed.
