### ISSUE TITLE
Implement scalability

### ISSUE THREAD

**Issue by goloroden** [thenativeweb/wolkenkit#90]
### What is this epic about?

Right now, we run every Docker container only as a single instance. But from its architecture, wolkenkit is able to run in a scaled way as well, and we could even scale the read model independent of the write model. We should add this to support things as load balancing and high availability.

### What needs to be done to complete this epic?

- [x] Scale the write model
  - [x] Ensure that the ordering of commands per aggregate stays consistent
- [ ] Scale the read model
- [ ] Scale flows
  - [ ] Ensure that flows only run a single time in response to events

**Comment by goloroden** [comment]
Will be part of v4, hence closed.
